/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

//um elefante incomoda muita gente huehuehue
import VO.Participante;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author a1590294
 */
public class Inscricao extends javax.swing.JFrame {

    /**
     * Creates new form Inscricao
     */
    public Inscricao() {
        initComponents();        
    }
    
    public void updateTabela(){
        DefaultTableModel model = ((DefaultTableModel) jTableMinicurso.getModel());
        model.setRowCount(0);
        RN.MiniCurso rnMinicurso = new RN.MiniCurso();
        rnMinicurso.getDadosTabela(model);
    }
     
    public void updateTabelaInscricao(){
        DefaultTableModel model = ((DefaultTableModel) jTableInscricao.getModel());
        model.setRowCount(0);
        RN.Inscricao rnInscricao = new RN.Inscricao();
        rnInscricao.getDadosTabela(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneInscricao = new javax.swing.JTabbedPane();
        jPanelMiniCurso = new javax.swing.JPanel();
        lblAssunto = new javax.swing.JLabel();
        txtAssunto = new javax.swing.JTextField();
        lblDuracao = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        btnInserirMiniCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMinicurso = new javax.swing.JTable();
        ftxtPreco = new javax.swing.JFormattedTextField();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanelInscricao = new javax.swing.JPanel();
        lblRA = new javax.swing.JLabel();
        txtRa = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblMinicurso = new javax.swing.JLabel();
        jComboBoxInscricao = new javax.swing.JComboBox();
        btnInscrever = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInscricao = new javax.swing.JTable();
        btnAlterarInscricao = new javax.swing.JButton();
        btnExcluirInscricao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAssunto.setText("Assunto:");

        lblDuracao.setText("Duracao:");

        lblPreco.setText("Preco:");

        btnInserirMiniCurso.setText("Inserir Minicurso");
        btnInserirMiniCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirMiniCursoActionPerformed(evt);
            }
        });

        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jTableMinicurso.setModel(modelo);
        modelo.addColumn("Assunto");
        modelo.addColumn("Duracao");
        modelo.addColumn("Preco");
        RN.MiniCurso tabela = new RN.MiniCurso();
        tabela.getDadosTabela(modelo);
        jScrollPane1.setViewportView(jTableMinicurso);

        DecimalFormat dFormat = new DecimalFormat("###.00") ;
        NumberFormatter formatter = new NumberFormatter(dFormat) ;
        formatter.setFormat(dFormat);
        formatter.setAllowsInvalid(false);
        ftxtPreco.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
        ftxtPreco.setValue(0);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMiniCursoLayout = new javax.swing.GroupLayout(jPanelMiniCurso);
        jPanelMiniCurso.setLayout(jPanelMiniCursoLayout);
        jPanelMiniCursoLayout.setHorizontalGroup(
            jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiniCursoLayout.createSequentialGroup()
                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMiniCursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanelMiniCursoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInserirMiniCurso)
                            .addGroup(jPanelMiniCursoLayout.createSequentialGroup()
                                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPreco)
                                    .addComponent(lblDuracao)
                                    .addComponent(lblAssunto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ftxtPreco)
                                    .addComponent(txtAssunto))))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanelMiniCursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        jPanelMiniCursoLayout.setVerticalGroup(
            jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiniCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssunto)
                    .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracao)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(ftxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnInserirMiniCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMiniCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnSair))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPaneInscricao.addTab("Mini Curso", jPanelMiniCurso);

        lblRA.setText("RA:");

        txtRa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRaFocusLost(evt);
            }
        });

        lblTipo.setText("Tipo:");

        lblStatus.setText("Status:");

        lblMinicurso.setText("Minicurso:");

        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        RN.Inscricao inscricao = new RN.Inscricao();
        inscricao.getDadosComboBox(modeloCombo);
        jComboBoxInscricao.setModel(modeloCombo);
        jComboBoxInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInscricaoActionPerformed(evt);
            }
        });

        btnInscrever.setText("Inscrever");
        btnInscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscreverActionPerformed(evt);
            }
        });

        DefaultTableModel modelo2 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jTableInscricao.setModel(modelo2);
        modelo2.addColumn("Assunto");
        modelo2.addColumn("Nome");
        modelo2.addColumn("Tipo");
        modelo2.addColumn("Status");
        RN.Inscricao tabela2 = new RN.Inscricao();
        tabela2.getDadosTabela(modelo2);
        jScrollPane2.setViewportView(jTableInscricao);

        btnAlterarInscricao.setText("Alterar");
        btnAlterarInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarInscricaoActionPerformed(evt);
            }
        });

        btnExcluirInscricao.setText("Excluir");
        btnExcluirInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirInscricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInscricaoLayout = new javax.swing.GroupLayout(jPanelInscricao);
        jPanelInscricao.setLayout(jPanelInscricaoLayout);
        jPanelInscricaoLayout.setHorizontalGroup(
            jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                        .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInscrever)
                                    .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                                        .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblStatus)
                                            .addComponent(lblTipo)
                                            .addComponent(lblRA))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInscricaoLayout.createSequentialGroup()
                                                .addComponent(lblMinicurso)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxInscricao, 0, 128, Short.MAX_VALUE))
                                            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRa)))))
                            .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnExcluirInscricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterarInscricao)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInscricaoLayout.setVerticalGroup(
            jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRA)
                    .addComponent(txtRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinicurso)
                    .addComponent(jComboBoxInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInscrever)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarInscricao)
                    .addComponent(btnExcluirInscricao))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPaneInscricao.addTab("Inscricao", jPanelInscricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneInscricao)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneInscricao, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnInserirMiniCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirMiniCursoActionPerformed
        // TODO add your handling code here:
        VO.MiniCurso minicurso = new VO.MiniCurso();
        minicurso.setAssunto(txtAssunto.getText());
        minicurso.setDuracao(txtDuracao.getText());
        minicurso.setPreco(Double.parseDouble(ftxtPreco.getText().replace(",", "."))); 
        RN.MiniCurso rnMinicurso = new RN.MiniCurso();
        rnMinicurso.validaDados(minicurso);
        updateTabela();
        
        
                
    }//GEN-LAST:event_btnInserirMiniCursoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(jTableMinicurso.getSelectedRowCount() > 0){
            VO.MiniCurso minicurso = new VO.MiniCurso();
            minicurso.setAssunto((String) jTableMinicurso.getValueAt(jTableMinicurso.getSelectedRow(), 0));
            //System.out.println(minicurso.getAssunto());
            RN.MiniCurso rnMinicurso = new RN.MiniCurso();
            rnMinicurso.excluirDado(minicurso);
            updateTabela();
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if(jTableMinicurso.getSelectedRowCount() > 0){
            VO.MiniCurso minicurso = new VO.MiniCurso();
            minicurso.setAssunto((String) jTableMinicurso.getValueAt(jTableMinicurso.getSelectedRow(), 0));
            minicurso.setDuracao((String) jTableMinicurso.getValueAt(jTableMinicurso.getSelectedRow(), 1));
            minicurso.setPreco((double) jTableMinicurso.getValueAt(jTableMinicurso.getSelectedRow(), 2));
            minicurso.setVelho(minicurso.getAssunto());
            InscricaoMiniCurso inscricao = new InscricaoMiniCurso();
            inscricao.setVisible(true);
            inscricao.setCampos(minicurso);
            this.dispose();
            
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtRaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRaFocusLost
        // TODO add your handling code here:
        try{
            Integer.parseInt(txtRa.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Valor de RA invalido!");
            txtRa.requestFocus();
        }
    }//GEN-LAST:event_txtRaFocusLost

    private void jComboBoxInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInscricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxInscricaoActionPerformed

    private void btnInscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscreverActionPerformed
        // TODO add your handling code here:
        VO.Inscricao inscricao = new VO.Inscricao();
        inscricao.setRa(Integer.parseInt(txtRa.getText()));
        inscricao.setTipo(txtTipo.getText());
        inscricao.setStatus(txtStatus.getText()); 
        inscricao.setMinicurso((String) jComboBoxInscricao.getSelectedItem());
        RN.Inscricao rnInscricao = new RN.Inscricao();
        rnInscricao.insertDados(inscricao);
        updateTabelaInscricao();
    }//GEN-LAST:event_btnInscreverActionPerformed

    private void btnExcluirInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirInscricaoActionPerformed
        // TODO add your handling code here:
        if(jTableInscricao.getSelectedRowCount() > 0){
            VO.Inscricao inscricao = new VO.Inscricao();
            inscricao.setMinicurso((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 0));
            inscricao.setNome((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 1));
            inscricao.setTipo((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 2));
            //System.out.println(minicurso.getAssunto());
            RN.Inscricao rnInscricao = new RN.Inscricao();
            rnInscricao.excluirDado(inscricao);
            updateTabelaInscricao();
        }
    }//GEN-LAST:event_btnExcluirInscricaoActionPerformed

    private void btnAlterarInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarInscricaoActionPerformed
        // TODO add your handling code here:
        if(jTableInscricao.getSelectedRowCount() > 0){
            VO.Inscricao inscricao = new VO.Inscricao();
            inscricao.setMinicurso((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 0));
            inscricao.setNome((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 1));
            inscricao.setTipo((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 2));
            inscricao.setStatus((String) jTableInscricao.getValueAt(jTableInscricao.getSelectedRow(), 3));
            InscricaoInscricao tela = new InscricaoInscricao();
            tela.setVisible(true);
            tela.setCampos(inscricao);
            this.dispose();
            
        }
    }//GEN-LAST:event_btnAlterarInscricaoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarInscricao;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirInscricao;
    private javax.swing.JButton btnInscrever;
    private javax.swing.JButton btnInserirMiniCurso;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftxtPreco;
    private javax.swing.JComboBox jComboBoxInscricao;
    private javax.swing.JPanel jPanelInscricao;
    private javax.swing.JPanel jPanelMiniCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneInscricao;
    private javax.swing.JTable jTableInscricao;
    private javax.swing.JTable jTableMinicurso;
    private javax.swing.JLabel lblAssunto;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblMinicurso;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblRA;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtRa;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
